package com.jason.mapper;

import com.jason.model.Core;
import com.jason.model.CoreExample;
import com.jason.model.CoreKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CoreMapper {
    /**
     * 查询学生所有课程的成绩
     * @param sno
     * @return
     */
    public List<Core> findAllScoreBySno(String sno);
    /**
     * 查询某学生某课程的成绩
     * @param map
     * @return
     */
    public Core findScoreBySnoAndCno(Map<String,String> map);
    /**
     * 学生选课
     * @param map
     */
    public void insertCore(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    int countByExample(CoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    int deleteByExample(CoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    int deleteByPrimaryKey(CoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    int insert(Core record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    int insertSelective(Core record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    List<Core> selectByExample(CoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    Core selectByPrimaryKey(CoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") Core record, @Param("example") CoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    int updateByExample(@Param("record") Core record, @Param("example") CoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    int updateByPrimaryKeySelective(Core record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    int updateByPrimaryKey(Core record);
}