package com.jason.model;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.cno
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classrom
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String classrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.grade
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.headmaster
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String headmaster;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.total_student
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private Integer totalStudent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.major_id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private Integer majorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.cno
     *
     * @return the value of class.cno
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.cno
     *
     * @param cno the value for class.cno
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classrom
     *
     * @return the value of class.classrom
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getClassrom() {
        return classrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classrom
     *
     * @param classrom the value for class.classrom
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setClassrom(String classrom) {
        this.classrom = classrom == null ? null : classrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.grade
     *
     * @return the value of class.grade
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.grade
     *
     * @param grade the value for class.grade
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.headmaster
     *
     * @return the value of class.headmaster
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getHeadmaster() {
        return headmaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.headmaster
     *
     * @param headmaster the value for class.headmaster
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setHeadmaster(String headmaster) {
        this.headmaster = headmaster == null ? null : headmaster.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.total_student
     *
     * @return the value of class.total_student
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Integer getTotalStudent() {
        return totalStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.total_student
     *
     * @param totalStudent the value for class.total_student
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setTotalStudent(Integer totalStudent) {
        this.totalStudent = totalStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.major_id
     *
     * @return the value of class.major_id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.major_id
     *
     * @param majorId the value for class.major_id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }
}