package com.jason.model;

import java.util.ArrayList;
import java.util.List;

public class ClassExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public ClassExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCnoIsNull() {
            addCriterion("cno is null");
            return (Criteria) this;
        }

        public Criteria andCnoIsNotNull() {
            addCriterion("cno is not null");
            return (Criteria) this;
        }

        public Criteria andCnoEqualTo(String value) {
            addCriterion("cno =", value, "cno");
            return (Criteria) this;
        }

        public Criteria andCnoNotEqualTo(String value) {
            addCriterion("cno <>", value, "cno");
            return (Criteria) this;
        }

        public Criteria andCnoGreaterThan(String value) {
            addCriterion("cno >", value, "cno");
            return (Criteria) this;
        }

        public Criteria andCnoGreaterThanOrEqualTo(String value) {
            addCriterion("cno >=", value, "cno");
            return (Criteria) this;
        }

        public Criteria andCnoLessThan(String value) {
            addCriterion("cno <", value, "cno");
            return (Criteria) this;
        }

        public Criteria andCnoLessThanOrEqualTo(String value) {
            addCriterion("cno <=", value, "cno");
            return (Criteria) this;
        }

        public Criteria andCnoLike(String value) {
            addCriterion("cno like", value, "cno");
            return (Criteria) this;
        }

        public Criteria andCnoNotLike(String value) {
            addCriterion("cno not like", value, "cno");
            return (Criteria) this;
        }

        public Criteria andCnoIn(List<String> values) {
            addCriterion("cno in", values, "cno");
            return (Criteria) this;
        }

        public Criteria andCnoNotIn(List<String> values) {
            addCriterion("cno not in", values, "cno");
            return (Criteria) this;
        }

        public Criteria andCnoBetween(String value1, String value2) {
            addCriterion("cno between", value1, value2, "cno");
            return (Criteria) this;
        }

        public Criteria andCnoNotBetween(String value1, String value2) {
            addCriterion("cno not between", value1, value2, "cno");
            return (Criteria) this;
        }

        public Criteria andClassromIsNull() {
            addCriterion("classrom is null");
            return (Criteria) this;
        }

        public Criteria andClassromIsNotNull() {
            addCriterion("classrom is not null");
            return (Criteria) this;
        }

        public Criteria andClassromEqualTo(String value) {
            addCriterion("classrom =", value, "classrom");
            return (Criteria) this;
        }

        public Criteria andClassromNotEqualTo(String value) {
            addCriterion("classrom <>", value, "classrom");
            return (Criteria) this;
        }

        public Criteria andClassromGreaterThan(String value) {
            addCriterion("classrom >", value, "classrom");
            return (Criteria) this;
        }

        public Criteria andClassromGreaterThanOrEqualTo(String value) {
            addCriterion("classrom >=", value, "classrom");
            return (Criteria) this;
        }

        public Criteria andClassromLessThan(String value) {
            addCriterion("classrom <", value, "classrom");
            return (Criteria) this;
        }

        public Criteria andClassromLessThanOrEqualTo(String value) {
            addCriterion("classrom <=", value, "classrom");
            return (Criteria) this;
        }

        public Criteria andClassromLike(String value) {
            addCriterion("classrom like", value, "classrom");
            return (Criteria) this;
        }

        public Criteria andClassromNotLike(String value) {
            addCriterion("classrom not like", value, "classrom");
            return (Criteria) this;
        }

        public Criteria andClassromIn(List<String> values) {
            addCriterion("classrom in", values, "classrom");
            return (Criteria) this;
        }

        public Criteria andClassromNotIn(List<String> values) {
            addCriterion("classrom not in", values, "classrom");
            return (Criteria) this;
        }

        public Criteria andClassromBetween(String value1, String value2) {
            addCriterion("classrom between", value1, value2, "classrom");
            return (Criteria) this;
        }

        public Criteria andClassromNotBetween(String value1, String value2) {
            addCriterion("classrom not between", value1, value2, "classrom");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(String value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(String value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(String value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(String value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(String value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(String value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLike(String value) {
            addCriterion("grade like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotLike(String value) {
            addCriterion("grade not like", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<String> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<String> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(String value1, String value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(String value1, String value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andHeadmasterIsNull() {
            addCriterion("headmaster is null");
            return (Criteria) this;
        }

        public Criteria andHeadmasterIsNotNull() {
            addCriterion("headmaster is not null");
            return (Criteria) this;
        }

        public Criteria andHeadmasterEqualTo(String value) {
            addCriterion("headmaster =", value, "headmaster");
            return (Criteria) this;
        }

        public Criteria andHeadmasterNotEqualTo(String value) {
            addCriterion("headmaster <>", value, "headmaster");
            return (Criteria) this;
        }

        public Criteria andHeadmasterGreaterThan(String value) {
            addCriterion("headmaster >", value, "headmaster");
            return (Criteria) this;
        }

        public Criteria andHeadmasterGreaterThanOrEqualTo(String value) {
            addCriterion("headmaster >=", value, "headmaster");
            return (Criteria) this;
        }

        public Criteria andHeadmasterLessThan(String value) {
            addCriterion("headmaster <", value, "headmaster");
            return (Criteria) this;
        }

        public Criteria andHeadmasterLessThanOrEqualTo(String value) {
            addCriterion("headmaster <=", value, "headmaster");
            return (Criteria) this;
        }

        public Criteria andHeadmasterLike(String value) {
            addCriterion("headmaster like", value, "headmaster");
            return (Criteria) this;
        }

        public Criteria andHeadmasterNotLike(String value) {
            addCriterion("headmaster not like", value, "headmaster");
            return (Criteria) this;
        }

        public Criteria andHeadmasterIn(List<String> values) {
            addCriterion("headmaster in", values, "headmaster");
            return (Criteria) this;
        }

        public Criteria andHeadmasterNotIn(List<String> values) {
            addCriterion("headmaster not in", values, "headmaster");
            return (Criteria) this;
        }

        public Criteria andHeadmasterBetween(String value1, String value2) {
            addCriterion("headmaster between", value1, value2, "headmaster");
            return (Criteria) this;
        }

        public Criteria andHeadmasterNotBetween(String value1, String value2) {
            addCriterion("headmaster not between", value1, value2, "headmaster");
            return (Criteria) this;
        }

        public Criteria andTotalStudentIsNull() {
            addCriterion("total_student is null");
            return (Criteria) this;
        }

        public Criteria andTotalStudentIsNotNull() {
            addCriterion("total_student is not null");
            return (Criteria) this;
        }

        public Criteria andTotalStudentEqualTo(Integer value) {
            addCriterion("total_student =", value, "totalStudent");
            return (Criteria) this;
        }

        public Criteria andTotalStudentNotEqualTo(Integer value) {
            addCriterion("total_student <>", value, "totalStudent");
            return (Criteria) this;
        }

        public Criteria andTotalStudentGreaterThan(Integer value) {
            addCriterion("total_student >", value, "totalStudent");
            return (Criteria) this;
        }

        public Criteria andTotalStudentGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_student >=", value, "totalStudent");
            return (Criteria) this;
        }

        public Criteria andTotalStudentLessThan(Integer value) {
            addCriterion("total_student <", value, "totalStudent");
            return (Criteria) this;
        }

        public Criteria andTotalStudentLessThanOrEqualTo(Integer value) {
            addCriterion("total_student <=", value, "totalStudent");
            return (Criteria) this;
        }

        public Criteria andTotalStudentIn(List<Integer> values) {
            addCriterion("total_student in", values, "totalStudent");
            return (Criteria) this;
        }

        public Criteria andTotalStudentNotIn(List<Integer> values) {
            addCriterion("total_student not in", values, "totalStudent");
            return (Criteria) this;
        }

        public Criteria andTotalStudentBetween(Integer value1, Integer value2) {
            addCriterion("total_student between", value1, value2, "totalStudent");
            return (Criteria) this;
        }

        public Criteria andTotalStudentNotBetween(Integer value1, Integer value2) {
            addCriterion("total_student not between", value1, value2, "totalStudent");
            return (Criteria) this;
        }

        public Criteria andMajorIdIsNull() {
            addCriterion("major_id is null");
            return (Criteria) this;
        }

        public Criteria andMajorIdIsNotNull() {
            addCriterion("major_id is not null");
            return (Criteria) this;
        }

        public Criteria andMajorIdEqualTo(Integer value) {
            addCriterion("major_id =", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotEqualTo(Integer value) {
            addCriterion("major_id <>", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdGreaterThan(Integer value) {
            addCriterion("major_id >", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("major_id >=", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdLessThan(Integer value) {
            addCriterion("major_id <", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdLessThanOrEqualTo(Integer value) {
            addCriterion("major_id <=", value, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdIn(List<Integer> values) {
            addCriterion("major_id in", values, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotIn(List<Integer> values) {
            addCriterion("major_id not in", values, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdBetween(Integer value1, Integer value2) {
            addCriterion("major_id between", value1, value2, "majorId");
            return (Criteria) this;
        }

        public Criteria andMajorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("major_id not between", value1, value2, "majorId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 18 14:12:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}