package com.jason.model;

public class Core extends CoreKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.score
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.term
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String term;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.score
     *
     * @return the value of core.score
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.score
     *
     * @param score the value for core.score
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.term
     *
     * @return the value of core.term
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.term
     *
     * @param term the value for core.term
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }
}