package com.jason.model;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.cno
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.major_id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private Integer majorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.cno
     *
     * @return the value of course.cno
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.cno
     *
     * @param cno the value for course.cno
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.major_id
     *
     * @return the value of course.major_id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.major_id
     *
     * @param majorId the value for course.major_id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }
}