package com.jason.model;

import java.util.List;

public class Department {
    private List<Student> students;//一个学院有多个学生

    public List<Student> getStudents() {
        return students;
    }

    public void setStudents(List<Student> students) {
        this.students = students;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.name
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.address
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.detail
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.total_student
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private Integer totalStudent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.id
     *
     * @return the value of department.id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.id
     *
     * @param id the value for department.id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.address
     *
     * @return the value of department.address
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.address
     *
     * @param address the value for department.address
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.detail
     *
     * @return the value of department.detail
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.detail
     *
     * @param detail the value for department.detail
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.total_student
     *
     * @return the value of department.total_student
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Integer getTotalStudent() {
        return totalStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.total_student
     *
     * @param totalStudent the value for department.total_student
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setTotalStudent(Integer totalStudent) {
        this.totalStudent = totalStudent;
    }

    @Override
    public String toString() {
        return "Department{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", address='" + address + '\'' +
                ", detail='" + detail + '\'' +
                ", totalStudent=" + totalStudent +
                '}';
    }
}