package com.jason.model;

import java.util.ArrayList;
import java.util.List;

public class DormExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public DormExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDnoIsNull() {
            addCriterion("dno is null");
            return (Criteria) this;
        }

        public Criteria andDnoIsNotNull() {
            addCriterion("dno is not null");
            return (Criteria) this;
        }

        public Criteria andDnoEqualTo(String value) {
            addCriterion("dno =", value, "dno");
            return (Criteria) this;
        }

        public Criteria andDnoNotEqualTo(String value) {
            addCriterion("dno <>", value, "dno");
            return (Criteria) this;
        }

        public Criteria andDnoGreaterThan(String value) {
            addCriterion("dno >", value, "dno");
            return (Criteria) this;
        }

        public Criteria andDnoGreaterThanOrEqualTo(String value) {
            addCriterion("dno >=", value, "dno");
            return (Criteria) this;
        }

        public Criteria andDnoLessThan(String value) {
            addCriterion("dno <", value, "dno");
            return (Criteria) this;
        }

        public Criteria andDnoLessThanOrEqualTo(String value) {
            addCriterion("dno <=", value, "dno");
            return (Criteria) this;
        }

        public Criteria andDnoLike(String value) {
            addCriterion("dno like", value, "dno");
            return (Criteria) this;
        }

        public Criteria andDnoNotLike(String value) {
            addCriterion("dno not like", value, "dno");
            return (Criteria) this;
        }

        public Criteria andDnoIn(List<String> values) {
            addCriterion("dno in", values, "dno");
            return (Criteria) this;
        }

        public Criteria andDnoNotIn(List<String> values) {
            addCriterion("dno not in", values, "dno");
            return (Criteria) this;
        }

        public Criteria andDnoBetween(String value1, String value2) {
            addCriterion("dno between", value1, value2, "dno");
            return (Criteria) this;
        }

        public Criteria andDnoNotBetween(String value1, String value2) {
            addCriterion("dno not between", value1, value2, "dno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoIsNull() {
            addCriterion("buildingNo is null");
            return (Criteria) this;
        }

        public Criteria andBuildingnoIsNotNull() {
            addCriterion("buildingNo is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingnoEqualTo(String value) {
            addCriterion("buildingNo =", value, "buildingno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoNotEqualTo(String value) {
            addCriterion("buildingNo <>", value, "buildingno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoGreaterThan(String value) {
            addCriterion("buildingNo >", value, "buildingno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoGreaterThanOrEqualTo(String value) {
            addCriterion("buildingNo >=", value, "buildingno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoLessThan(String value) {
            addCriterion("buildingNo <", value, "buildingno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoLessThanOrEqualTo(String value) {
            addCriterion("buildingNo <=", value, "buildingno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoLike(String value) {
            addCriterion("buildingNo like", value, "buildingno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoNotLike(String value) {
            addCriterion("buildingNo not like", value, "buildingno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoIn(List<String> values) {
            addCriterion("buildingNo in", values, "buildingno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoNotIn(List<String> values) {
            addCriterion("buildingNo not in", values, "buildingno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoBetween(String value1, String value2) {
            addCriterion("buildingNo between", value1, value2, "buildingno");
            return (Criteria) this;
        }

        public Criteria andBuildingnoNotBetween(String value1, String value2) {
            addCriterion("buildingNo not between", value1, value2, "buildingno");
            return (Criteria) this;
        }

        public Criteria andDoornoIsNull() {
            addCriterion("doorNo is null");
            return (Criteria) this;
        }

        public Criteria andDoornoIsNotNull() {
            addCriterion("doorNo is not null");
            return (Criteria) this;
        }

        public Criteria andDoornoEqualTo(String value) {
            addCriterion("doorNo =", value, "doorno");
            return (Criteria) this;
        }

        public Criteria andDoornoNotEqualTo(String value) {
            addCriterion("doorNo <>", value, "doorno");
            return (Criteria) this;
        }

        public Criteria andDoornoGreaterThan(String value) {
            addCriterion("doorNo >", value, "doorno");
            return (Criteria) this;
        }

        public Criteria andDoornoGreaterThanOrEqualTo(String value) {
            addCriterion("doorNo >=", value, "doorno");
            return (Criteria) this;
        }

        public Criteria andDoornoLessThan(String value) {
            addCriterion("doorNo <", value, "doorno");
            return (Criteria) this;
        }

        public Criteria andDoornoLessThanOrEqualTo(String value) {
            addCriterion("doorNo <=", value, "doorno");
            return (Criteria) this;
        }

        public Criteria andDoornoLike(String value) {
            addCriterion("doorNo like", value, "doorno");
            return (Criteria) this;
        }

        public Criteria andDoornoNotLike(String value) {
            addCriterion("doorNo not like", value, "doorno");
            return (Criteria) this;
        }

        public Criteria andDoornoIn(List<String> values) {
            addCriterion("doorNo in", values, "doorno");
            return (Criteria) this;
        }

        public Criteria andDoornoNotIn(List<String> values) {
            addCriterion("doorNo not in", values, "doorno");
            return (Criteria) this;
        }

        public Criteria andDoornoBetween(String value1, String value2) {
            addCriterion("doorNo between", value1, value2, "doorno");
            return (Criteria) this;
        }

        public Criteria andDoornoNotBetween(String value1, String value2) {
            addCriterion("doorNo not between", value1, value2, "doorno");
            return (Criteria) this;
        }

        public Criteria andTotalnumIsNull() {
            addCriterion("totalNum is null");
            return (Criteria) this;
        }

        public Criteria andTotalnumIsNotNull() {
            addCriterion("totalNum is not null");
            return (Criteria) this;
        }

        public Criteria andTotalnumEqualTo(Integer value) {
            addCriterion("totalNum =", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumNotEqualTo(Integer value) {
            addCriterion("totalNum <>", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumGreaterThan(Integer value) {
            addCriterion("totalNum >", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("totalNum >=", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumLessThan(Integer value) {
            addCriterion("totalNum <", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumLessThanOrEqualTo(Integer value) {
            addCriterion("totalNum <=", value, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumIn(List<Integer> values) {
            addCriterion("totalNum in", values, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumNotIn(List<Integer> values) {
            addCriterion("totalNum not in", values, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumBetween(Integer value1, Integer value2) {
            addCriterion("totalNum between", value1, value2, "totalnum");
            return (Criteria) this;
        }

        public Criteria andTotalnumNotBetween(Integer value1, Integer value2) {
            addCriterion("totalNum not between", value1, value2, "totalnum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dorm
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 18 14:12:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dorm
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}