package com.jason.model;

public class Major {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.name
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.datail
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private String datail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.department_id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    private Integer departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.id
     *
     * @return the value of major.id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.id
     *
     * @param id the value for major.id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.name
     *
     * @return the value of major.name
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.name
     *
     * @param name the value for major.name
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.datail
     *
     * @return the value of major.datail
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public String getDatail() {
        return datail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.datail
     *
     * @param datail the value for major.datail
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setDatail(String datail) {
        this.datail = datail == null ? null : datail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.department_id
     *
     * @return the value of major.department_id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.department_id
     *
     * @param departmentId the value for major.department_id
     *
     * @mbggenerated Thu Apr 18 14:12:51 CST 2019
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
}