package com.jason.model;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.sex
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.age
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.jobtitle
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    private String jobtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.username
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.password
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.classno
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    private String classno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.cno
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    private String cno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.sex
     *
     * @return the value of teacher.sex
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.sex
     *
     * @param sex the value for teacher.sex
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.age
     *
     * @return the value of teacher.age
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.age
     *
     * @param age the value for teacher.age
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.jobtitle
     *
     * @return the value of teacher.jobtitle
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public String getJobtitle() {
        return jobtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.jobtitle
     *
     * @param jobtitle the value for teacher.jobtitle
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public void setJobtitle(String jobtitle) {
        this.jobtitle = jobtitle == null ? null : jobtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.username
     *
     * @return the value of teacher.username
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.username
     *
     * @param username the value for teacher.username
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.password
     *
     * @return the value of teacher.password
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.password
     *
     * @param password the value for teacher.password
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.classno
     *
     * @return the value of teacher.classno
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public String getClassno() {
        return classno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.classno
     *
     * @param classno the value for teacher.classno
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public void setClassno(String classno) {
        this.classno = classno == null ? null : classno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.cno
     *
     * @return the value of teacher.cno
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.cno
     *
     * @param cno the value for teacher.cno
     *
     * @mbggenerated Tue Apr 23 14:28:55 CST 2019
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", sex='" + sex + '\'' +
                ", age=" + age +
                ", jobtitle='" + jobtitle + '\'' +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", classno='" + classno + '\'' +
                ", cno='" + cno + '\'' +
                '}';
    }
}